apply from: 'gradle/scripts/helpers.gradle'

repositories {
    // Other repositories described by default:
    // CleanroomMC: https://maven.cleanroommc.com
    exclusiveContent {
        forRepository {
            maven {
                name 'CurseMaven'
                url 'https://cursemaven.com'
            }
        }
        filter {
            includeGroup 'curse.maven'
        }
    }
    exclusiveContent {
        forRepository {
            maven {
                name 'Modrinth'
                url 'https://api.modrinth.com/maven'
            }
        }
        filter {
            includeGroup 'maven.modrinth'
        }
    }

    exclusiveContent {
        forRepository {
            maven {
                url = "http://maven.blamejared.com"
                allowInsecureProtocol true
            }
        }
        filter {
            includeGroup 'vazkii.patchouli'
            includeGroup 'blusunrize'
            includeGroup 'CraftTweaker2'
        }
    }

    exclusiveContent {
        forRepository {
            maven {
                url = "https://dvs1.progwml6.com/files/maven"
            }
        }
        filter {
            includeGroup 'slimeknights.mantle'
            includeGroup 'slimeknights'
        }
    }

    mavenLocal() // Must be last for caching to work
}

dependencies {
    // Include StripLatestForgeRequirements by default for the dev env, saves everyone a hassle
    runtimeOnly 'com.cleanroommc:strip-latest-forge-requirements:1.0'
    // Include OSXNarratorBlocker by default for the dev env, for M1+ Macs
    runtimeOnly 'com.cleanroommc:osxnarratorblocker:1.0'

    // MMLib v2.3.0
    compileOnly rfg.deobf("curse.maven:MMLib-368098:3254750")

    compileOnly "vazkii.patchouli:Patchouli:1.0-23.6"
    compileOnly "blusunrize:ImmersiveEngineering:0.12-92-559"

    implementation 'mezz:jei:4.28.1'

    // JEI Integration v1.6.0
    compileOnly rfg.deobf("curse.maven:jeiintegration-265917:2951731")

    // ProjectPotman v1.0.0
    compileOnly rfg.deobf("curse.maven:proj_pot-432017:3152243")

    // TerraFirmaCraft v1.7.23.181
    compileOnly rfg.deobf("curse.maven:tfc-302973:3645502")

    // ToughAsNails v3.1.0.141
    compileOnly rfg.deobf("curse.maven:toughasnails-246391:2710969")

    // Hwyla v1.8.26-B41
    compileOnly rfg.deobf("curse.maven:hwyla-253449:2568751")

    // Cuisine v0.5.22-build929
    compileOnly rfg.deobf("curse.maven:cuisine-303694:2932722")

    compileOnly "slimeknights.mantle:Mantle:1.12-1.3.3.55"

    compileOnly "slimeknights:TConstruct:1.12.2-2.13.0.183"

    def ctVersion = "4.1.20.705"

    api("CraftTweaker2:CraftTweaker2-MC1120-Main:1.12-$ctVersion") {
        exclude group: 'org.ow2.asm'
    }
    api "CraftTweaker2:CraftTweaker2-API:$ctVersion"
    api "CraftTweaker2:ZenScript:$ctVersion"
}